### PR TITLE
Test flake #42

### PR DESCRIPTION
**Pull request by mrturkmen06**

### CODE REVIEW

**Comment by mrturkmen06** [comment]
This part ? 

```
- name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
```

**Comment by kidmose** [comment]
@mrturkmen06 Exactly that part :+1:

**Comment by mrturkmen06** [comment]
So, @kidmose, how many errors could be acceptable from flake8 ? 
I could not entirely understand `Can we somehow test that the number of errors doesn't go up?` statement, I'm sorry.

**Comment by kidmose** [comment]
> So, @kidmose, how many errors could be acceptable from flake8 ?
> I could not entirely understand `Can we somehow test that the number of errors doesn't go up?` statement, I'm sorry. Could you clarify it a little bit further ?

Sure.
We currently have pep8 errors. But we don't want to deal with all of them right now. 
We want the test fail if commits introduce more errors.
We want test to pass if commit does not introduce more errors.

Let's say the current error count is 500 (a guess, adjust to actual value), then the above can be achieve with something like this (roughly bash, but don't expect it to run as is):

    if [[ ${flake8 ... | grep 'error|warn' | wc -l} -gt 500 ]]
    then:
      exit 1 # fail test because error count is higher than hardcoded number
    else: 
      exit 0 # pass because error count did not go up
    fi

We can then adjust the hardcoded limit downwards over time.

Does that make sense?

**Comment by kidmose** [comment]
Sorry for not getting with this. I'll try and bring it back to life :)

I'm not as well versed in github actions as you are, @mrturkmen06 , but is seems that this fails because the tests in `.github/workflows/pythonpackage.yml ` is run on on windows, where the bash code fails to run in powershell?

I don't see a reason why the pep8 linting has to be done on all OSs, as it pertains only to the code and the standard, without actual running the code in an environment. 
Should it perhaps be put in a job of it's own, without the `jobs.test.matrix.os: [windows-latest,ubuntu-latest, macOS-latest]` config value, but simply a `jobs.pep8-linting.runs-on: ubuntu-latest`?

**Comment by kidmose** [comment]
Since my last comment, I have created #67, which enforces that the pep8 validation error count stays below a hard-coded limit (Which should be lowered as the error count goes down), in a new `lint` step.

I still think the auto-pep8 functionality can be relevant; 
For certain until we reach 0 errors, perhaps also afterwards as an aid to fix trivial errors that makes it into a PR, so it is fixed anyway before review.

Is it possible to merge the `autopep8` (below) with the `lint` job in #67, such that pep8 errors are autocorrected in PRs?
https://github.com/aau-network-security/richkit/blob/28b866c829db470a0b9c14847d47485e6589b6ec/.github/workflows/formatpythoncode.yml#L8-L22

(Also, there seems to be bunch of unrelated changes, that doesn't pertain to #42 , which has made it's way into this PR. Please remove those before we can merge.)

**Pull request merged**
