### PR TITLE
update docs, keep master branch updated with develop

### PR DESCRIPTION
**Pull request by mrturkmen06**
- Merging into master and releasing new version will re-compile docs and keep master and develop updated. 
- Afterwards, cleaning other branches (which are not useful anymore) could be option too.

### CODE REVIEW

**Comment by mrturkmen06** [comment]
Before merging it into master, deciding on development status of richkit could be nice as well. 

` 'Development Status :: 3 - Alpha',` in [setup.py](https://github.com/aau-network-security/richkit/blob/26e47b192194241cfd5e1d7ba01a254cf5f487e9/setup.py#L33) file

**Comment by kidmose** [comment]
> Before merging it into master, deciding on development status of richkit could be nice as well.
> 
> ` 'Development Status :: 3 - Alpha',` in [setup.py](https://github.com/aau-network-security/richkit/blob/26e47b192194241cfd5e1d7ba01a254cf5f487e9/setup.py#L33) file

Sure. Do you have a proposal for what this should be, or is there a standard that we can lean on to decide this?

**Comment by mrturkmen06** [comment]
> > Before merging it into master, deciding on development status of richkit could be nice as well.
> > ` 'Development Status :: 3 - Alpha',` in [setup.py](https://github.com/aau-network-security/richkit/blob/26e47b192194241cfd5e1d7ba01a254cf5f487e9/setup.py#L33) file
> 
> Sure. Do you have a proposal for what this should be, or is there a standard that we can lean on to decide this?

When I have check steps on software development cycle, it says that, after alpha, releasing beta would be next step. Changing it into beta would be nice. What is your suggestion @gianmarcomennecozzi and @kidmose ?

image

**Comment by kidmose** [comment]
I'm fine with calling it a beta now :)

**Pull request merged**
